/**
 * Generated by scripts/build-people.py: hand-drawn pixel parts for the people in Scam Town
 * (16x24 when put together: head, neck, body, legs). people.ts assembles the frames.
 * Edit the script, not this file.
 */
export const PERSON_W = 16
export const PERSON_H = 24
export const HEADS: Record<string, Record<string, readonly string[]>> = {
  short: {
    down: ['......oooo......', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohHhhhhhdo...', '...ohhsssshdo...', '....osssssSo....', '....osesseSo....', '....osesseSo....', '....ossmmSSo....', '.....oSssSo.....'],
    up: ['......oooo......', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohHhhhhhdo...', '...ohhhhhhhdo...', '...ohhhhhhddo...', '....ohhhhddo....', '....odhhhddo....', '....osddddSo....', '.....oSssSo.....'],
    right: ['......ooooo.....', '....oohHhhhoo...', '...ohHHhhhhhho..', '...ohHhhhhssdo..', '...ohhhhhsssSo..', '...odhhhssssSo..', '....odhhssesSo..', '....oddhssesSo..', '.....odsssmSo...', '.....ooSssSo....'],
  },
  long: {
    down: ['......oooo......', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohHhhhhhdo...', '...ohhsssshdo...', '...ohsssssSdo...', '...ohsesseSdo...', '...ohsesseSdo...', '...ohssmmSSdo...', '...ohdSssSddo...'],
    up: ['......oooo......', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohHhhhhhdo...', '...ohhhhhhhdo...', '...ohhhhhhhdo...', '...ohhhhhhddo...', '...ohhhhhhddo...', '...odhhhhhddo...', '....oddhhddo....'],
    right: ['......ooooo.....', '....oohHhhhoo...', '...ohHHhhhhhho..', '...ohHhhhhssdo..', '...ohhhhhsssSo..', '...ohhhhssssSo..', '...ohhhhssesSo..', '...odhhhssesSo..', '...odhhosssmSo..', '...oddo.oSssSo..'],
  },
  cap: {
    down: ['.....oooooo.....', '....otttttto....', '...otttttttto...', '...ocCccccckk...', '...oooooooooo...', '....ohsssshd....', '....osesseSo....', '....osesseSo....', '....ossmmSSo....', '.....oSssSo.....'],
    up: ['.....oooooo.....', '....otttttto....', '...otttttttto...', '...otttttttto...', '...okkkkkkkko...', '...ohhhhhhddo...', '....ohhhhddo....', '....odhhhddo....', '....osddddSo....', '.....oSssSo.....'],
    right: ['.....oooooo.....', '....otttttto....', '...ottttttttoooo', '...okkkkkkkkkkko', '...ohhhhhsssSo..', '...odhhhssssSo..', '....odhhssesSo..', '....oddhssesSo..', '.....odsssmSo...', '.....ooSssSo....'],
  },
  bun: {
    down: ['......oooo......', '.....ohHhho.....', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohhsssshdo...', '....osssssSo....', '....osesseSo....', '....osesseSo....', '....ossmmSSo....', '.....oSssSo.....'],
    up: ['......oooo......', '.....ohHhho.....', '....oohHhhoo....', '...ohHHhhhhdo...', '...ohhhhhhhdo...', '...ohhhhhhddo...', '....ohhhhddo....', '....odhhhddo....', '....osddddSo....', '.....oSssSo.....'],
    right: ['....ooo.........', '...ohHho........', '...ohhdooooo....', '...odhHHhhhhho..', '...ohhhhhsssSo..', '...odhhhssssSo..', '....odhhssesSo..', '....oddhssesSo..', '.....odsssmSo...', '.....ooSssSo....'],
  },
}
export const NECK: Record<string, string> = {
  down: '......oSSo......',
  up: '......oSSo......',
  right: '......oSSo......',
}
export const BODIES: Record<string, readonly string[]> = {
  down: ['...ooCcttckoo...', '..oCCccttcckko..', '..oCcccttccckk..', '..oCoccccccoko..', '..oCocccccckko..', '..osocccccckSo..', '..oSottttttoSo..'],
  up: ['...ooCcccckoo...', '..oCCcccccccko..', '..oCcccccccckk..', '..oCoccccccoko..', '..oCocccccckko..', '..osocccccckSo..', '..oSottttttoSo..'],
  right: ['....ooCccckoo...', '....oCCcCkcko...', '....oCccCkcko...', '....oCccCkcko...', '....oCccCkcko...', '....oCccsSkko...', '....ottttttto...'],
  right_swing: ['....ooCccckoo...', '....oCCccCkko...', '....oCcccCkko...', '....oCccccCko...', '....oCcccccsSo..', '....oCcccccko...', '....ottttttto...'],
}
export const KURTA: Record<string, string> = {
  down: '...oCccccckko...',
  up: '...oCcccccko....',
  right: '....oCcccccko...',
}
export const LEGS: Record<string, Record<string, readonly string[]>> = {
  down: {
    stand: ['....oppppPPo....', '....oppooPPo....', '....oppo.oPP....', '....oppo.oPo....', '....offo.oFo....', '....oooo.ooo....'],
    stepA: ['....oppppPPo....', '....oppooPPo....', '...oppo..oPo....', '...oppo..oPo....', '...offo..oFo....', '...oooo..ooo....'],
    stepB: ['....oppppPPo....', '....oppooPPo....', '....opo..oPPo...', '....opo..oPPo...', '....ofo..oFFo...', '....ooo..oooo...'],
  },
  right: {
    stand: ['.....opppPo.....', '.....opppPo.....', '.....oppPPo.....', '.....oppPPo.....', '.....offFFoo....', '.....ooooooo....'],
    stepA: ['.....opppPPo....', '....oppooPPo....', '...oppo..oPPo...', '...opo....oPo...', '..offo....oFFo..', '..oooo....oooo..'],
    stepB: ['.....opppPo.....', '.....oppPPo.....', '....oppooPo.....', '....opo.oPo.....', '....ofo.oFFo....', '....ooo.oooo....'],
  },
}
