import type { ScamDef } from '@/engine/types'

/**
 * The Scam Squad (Section 4.5): original, slightly comic villains. All copy lives in i18n.
 * Two decoys are real messages; treating them as scams costs nothing.
 */
export const SCAMS: ScamDef[] = [
  {
    id: 'phisher',
    nameKey: 'scam.phisher.name',
    emoji: '🎣',
    color: '#FF4D6D',
    channel: 'sms',
    senderKey: 'scam.phisher.sender',
    hookKey: 'scam.phisher.hook',
    personalHookKey: 'scam.phisher.personal',
    trigger: { type: 'firstShortfall' },
    urgencySeconds: 60,
    tellKeys: ['tell.urgency', 'tell.oddLink', 'tell.genericGreeting'],
    comply: { loss: 2_500, effects: [{ kind: 'privacy', delta: -40 }, { kind: 'stress', delta: 10 }] },
    codex: { howKey: 'scam.phisher.how', whatToDoKey: 'scam.phisher.do' },
  },
  {
    id: 'loan_shark',
    nameKey: 'scam.loanShark.name',
    emoji: '🦈',
    color: '#5B4B6B',
    channel: 'ad',
    senderKey: 'scam.loanShark.sender',
    hookKey: 'scam.loanShark.hook',
    personalHookKey: 'scam.loanShark.personal',
    trigger: { type: 'gapForeseen', minDay: 2 },
    urgencySeconds: 90,
    tellKeys: ['tell.noDocuments', 'tell.preApproved', 'tell.appPermissions'],
    comply: {
      loss: 0,
      cashIn: 15_000,
      weeklyFee: 1_500,
      effects: [{ kind: 'privacy', delta: -30 }, { kind: 'stress', delta: 15 }, { kind: 'flag', flag: 'loanSharkDebt' }],
    },
    codex: { howKey: 'scam.loanShark.how', whatToDoKey: 'scam.loanShark.do' },
  },
  {
    id: 'impersonator',
    nameKey: 'scam.impersonator.name',
    emoji: '🎭',
    color: '#D9734E',
    channel: 'chat',
    senderKey: 'scam.impersonator.sender',
    hookKey: 'scam.impersonator.hook',
    personalHookKey: 'scam.impersonator.personal',
    trigger: { type: 'dayRange', from: 17, to: 19 },
    urgencySeconds: 60,
    tellKeys: ['tell.newNumber', 'tell.cannotCall', 'tell.urgentMoney'],
    comply: { loss: 5_000, effects: [{ kind: 'stress', delta: 10 }] },
    codex: { howKey: 'scam.impersonator.how', whatToDoKey: 'scam.impersonator.do' },
  },
  {
    id: 'otp_snatcher',
    nameKey: 'scam.otp.name',
    emoji: '🔑',
    color: '#1E2A44',
    channel: 'call',
    senderKey: 'scam.otp.sender',
    hookKey: 'scam.otp.hook',
    personalHookKey: 'scam.otp.personal',
    trigger: { type: 'payday', minDay: 2 },
    urgencySeconds: 45,
    tellKeys: ['tell.askCode', 'tell.callerId', 'tell.pressure'],
    comply: { loss: 8_000, effects: [{ kind: 'stress', delta: 15 }] },
    codex: { howKey: 'scam.otp.how', whatToDoKey: 'scam.otp.do' },
  },
  {
    id: 'fine_print',
    nameKey: 'scam.finePrint.name',
    emoji: '📜',
    color: '#F5C26B',
    channel: 'sms',
    senderKey: 'scam.finePrint.sender',
    hookKey: 'scam.finePrint.hook',
    trigger: { type: 'afterOffer', flags: ['loanApp', 'instalments'], fallbackDay: 6 },
    urgencySeconds: 120,
    tellKeys: ['tell.asterisk', 'tell.acceptNow', 'tell.noTotalCost'],
    comply: { loss: 0, laterLoss: { amount: 1_200, daysAfter: 7 }, effects: [{ kind: 'privacy', delta: -10 }] },
    codex: { howKey: 'scam.finePrint.how', whatToDoKey: 'scam.finePrint.do' },
  },
  {
    id: 'prize_ghost',
    nameKey: 'scam.prizeGhost.name',
    emoji: '👻',
    color: '#8FB08A',
    channel: 'sms',
    senderKey: 'scam.prizeGhost.sender',
    hookKey: 'scam.prizeGhost.hook',
    personalHookKey: 'scam.prizeGhost.personal',
    trigger: { type: 'eventDay', eventId: 'festival' },
    urgencySeconds: 60,
    tellKeys: ['tell.payToWin', 'tell.idPhoto', 'tell.capsUrgency'],
    comply: { loss: 999, effects: [{ kind: 'privacy', delta: -30 }] },
    codex: { howKey: 'scam.prizeGhost.how', whatToDoKey: 'scam.prizeGhost.do' },
  },
  {
    id: 'job_recruiter',
    nameKey: 'scam.jobRecruiter.name',
    emoji: '🧳',
    color: '#6EC6FF',
    channel: 'chat',
    senderKey: 'scam.jobRecruiter.sender',
    hookKey: 'scam.jobRecruiter.hook',
    trigger: { type: 'day', day: 14 },
    urgencySeconds: 90,
    tellKeys: ['tell.feeUpfront', 'tell.tooGood', 'tell.todayOnly'],
    comply: { loss: 20_000, effects: [{ kind: 'stress', delta: 25 }] },
    codex: { howKey: 'scam.jobRecruiter.how', whatToDoKey: 'scam.jobRecruiter.do' },
  },
  {
    id: 'investment_guru',
    nameKey: 'scam.guru.name',
    emoji: '📈',
    color: '#4ADE80',
    channel: 'chat',
    senderKey: 'scam.guru.sender',
    hookKey: 'scam.guru.hook',
    personalHookKey: 'scam.guru.personal',
    trigger: { type: 'afterPayday', daysAfter: 2, minDay: 15 },
    urgencySeconds: 90,
    tellKeys: ['tell.guaranteed', 'tell.doubleIn30', 'tell.limitedSeats'],
    comply: { loss: 3_000, effects: [{ kind: 'flag', flag: 'guruReturns' }] },
    codex: { howKey: 'scam.guru.how', whatToDoKey: 'scam.guru.do' },
  },
  // ---- Decoys: real messages ----
  {
    id: 'bank_notice',
    nameKey: 'scam.bankNotice.name',
    emoji: '🏦',
    color: '#1E2A44',
    channel: 'sms',
    senderKey: 'scam.bankNotice.sender',
    hookKey: 'scam.bankNotice.hook',
    trigger: { type: 'day', day: 7 },
    urgencySeconds: 0,
    tellKeys: [],
    comply: { loss: 0 },
    decoy: true,
    codex: { howKey: 'scam.bankNotice.how', whatToDoKey: 'scam.bankNotice.do' },
  },
  {
    id: 'partner_real',
    nameKey: 'scam.partnerReal.name',
    emoji: '💬',
    color: '#8FB08A',
    channel: 'chat',
    senderKey: 'scam.partnerReal.sender',
    hookKey: 'scam.partnerReal.hook',
    trigger: { type: 'day', day: 18 },
    urgencySeconds: 0,
    tellKeys: [],
    comply: { loss: 0 },
    decoy: true,
    codex: { howKey: 'scam.partnerReal.how', whatToDoKey: 'scam.partnerReal.do' },
  },
]

export const SCAMS_BY_ID: Record<string, ScamDef> = Object.fromEntries(SCAMS.map((s) => [s.id, s]))

/** Shield points per response on a real scam (plus 1 per tell spotted). */
export const SHIELD_POINTS: Record<string, number> = { verify: 3, wait: 3, block: 2, ask: 2, comply: 0 }
