#!/usr/bin/env python3
"""
Build the walk grid for the team's town map (public/sprites/town-map.png).

Each 4x4-pixel cell is walkable when it is mostly ground (grass, cobblestone, dirt or
plaza) with almost no dark outline pixels; fences, trees, buildings, stalls and water
are blocked. Single stray specks on roads are smoothed away, cells listed in OPEN/BLOCK
are forced, and only the main connected area is kept (yards behind fences, tree tops and
roofs become solid). Output: src/walk/collision.ts (and a preview with --preview DIR).
Run: python3 scripts/build-collision.py [--preview DIR]
"""
import colorsys, pathlib, sys
from collections import deque
from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parent.parent
MAP = ROOT / 'public/sprites/town-map.png'
OUT = ROOT / 'src/walk/collision.ts'
C = 4

# Hand corrections in map pixels: (x, y, w, h).
OPEN = [
    (180, 172, 32, 12),  # in front of the clock tower door
    (24, 280, 24, 12),   # bank steps
]
BLOCK = [
    (296, 0, 9, 537),    # the frame on the right edge of the artwork
]


def kind(p):
    r, g, b = [c / 255 for c in p]
    h, s, v = colorsys.rgb_to_hsv(r, g, b)
    h *= 360
    if v < 0.36:
        return 'dark'
    if 180 <= h <= 260 and s > 0.25:
        return 'water'
    if 62 <= h <= 150 and s > 0.22 and v >= 0.40:
        return 'ground'
    if 22 <= h <= 58 and s <= 0.34 and v >= 0.44:
        return 'ground'
    if 20 <= h <= 46 and 0.34 < s <= 0.62 and 0.55 <= v <= 0.82:
        return 'ground'
    return 'other'


def build():
    im = Image.open(MAP).convert('RGB')
    W, H = im.size
    px = im.load()
    cols, rows = (W + C - 1) // C, (H + C - 1) // C
    cell = [[False] * cols for _ in range(rows)]
    for cy in range(rows):
        for cx in range(cols):
            n = ground = dark = 0
            for y in range(cy * C, min(H, cy * C + C)):
                for x in range(cx * C, min(W, cx * C + C)):
                    k = kind(px[x, y])
                    n += 1
                    ground += k == 'ground'
                    dark += k == 'dark'
            cell[cy][cx] = ground / n >= 0.75 and dark / n <= 0.12
    # Smooth: a blocked cell with three or four open neighbours is a speck on the road.
    fixed = [row[:] for row in cell]
    for cy in range(rows):
        for cx in range(cols):
            if not cell[cy][cx]:
                open_n = sum(1 for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)) if 0 <= cx + dx < cols and 0 <= cy + dy < rows and cell[cy + dy][cx + dx])
                if open_n >= 3:
                    fixed[cy][cx] = True
    cell = fixed

    def paint(rects, value):
        for x, y, w, h in rects:
            for cy in range(y // C, min(rows, (y + h + C - 1) // C)):
                for cx in range(x // C, min(cols, (x + w + C - 1) // C)):
                    cell[cy][cx] = value

    paint(OPEN, True)
    paint(BLOCK, False)
    # Keep the biggest connected area.
    seen = [[False] * cols for _ in range(rows)]
    best = []
    for sy in range(rows):
        for sx in range(cols):
            if cell[sy][sx] and not seen[sy][sx]:
                comp, q = [], deque([(sx, sy)])
                seen[sy][sx] = True
                while q:
                    x, y = q.popleft()
                    comp.append((x, y))
                    for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                        nx, ny = x + dx, y + dy
                        if 0 <= nx < cols and 0 <= ny < rows and cell[ny][nx] and not seen[ny][nx]:
                            seen[ny][nx] = True
                            q.append((nx, ny))
                if len(comp) > len(best):
                    best = comp
    keep = set(best)
    grid = [''.join('.' if (x, y) in keep else '#' for x in range(cols)) for y in range(rows)]
    return im, grid, cols, rows


def main():
    im, grid, cols, rows = build()
    body = ',\n'.join(f"  '{r}'" for r in grid)
    OUT.write_text(
        '/**\n * Generated by scripts/build-collision.py from the team\'s town map. Do not edit by hand:\n'
        ' * change OPEN/BLOCK in the script and run it again. "." is walkable, "#" is blocked.\n */\n'
        f'export const CELL = {C}\nexport const GRID_COLS = {cols}\nexport const GRID_ROWS = {rows}\n'
        f'export const TOWN_GRID: readonly string[] = [\n{body},\n]\n'
    )
    print('wrote', OUT.relative_to(ROOT), cols, 'x', rows, sum(r.count('.') for r in grid), 'walkable cells')
    if '--preview' in sys.argv:
        d = pathlib.Path(sys.argv[sys.argv.index('--preview') + 1])
        s = 3
        W, H = im.size
        big = im.resize((W * s, H * s), Image.NEAREST).convert('RGBA')
        ov = Image.new('RGBA', big.size, (0, 0, 0, 0))
        dr = ImageDraw.Draw(ov)
        for cy, row in enumerate(grid):
            for cx, ch in enumerate(row):
                if ch == '#':
                    dr.rectangle([cx * C * s, cy * C * s, (cx + 1) * C * s - 1, (cy + 1) * C * s - 1], fill=(255, 0, 0, 80))
        big.alpha_composite(ov)
        big.crop((0, 0, W * s, H * s // 2)).save(d / 'col_top.png')
        big.crop((0, H * s // 2, W * s, H * s)).save(d / 'col_bot.png')


if __name__ == '__main__':
    main()
