#!/usr/bin/env python3
"""
Recolour the vendor pixel art into the game's single palette (src/ui/palette.ts)
and give every piece the same 1 px ink outline.

Input:  public/assets/vendor/**   (originals + licences, never edited)
Output: src/assets/pixel/ui/*.png      compact nine-slice panels and buttons
        src/assets/pixel/tiles.png     Tiny Town tiles, packed 12 per row, 16x16
Run:    python3 scripts/unify-assets.py   (needs Pillow)
"""
import pathlib, re, warnings
from PIL import Image

ROOT = pathlib.Path(__file__).resolve().parent.parent
VENDOR = ROOT / 'public/assets/vendor'
OUT = ROOT / 'src/assets/pixel'
PAL_TS = (ROOT / 'src/ui/palette.ts').read_text()
PALETTE = {k: tuple(int(v[i:i + 2], 16) for i in (1, 3, 5)) for k, v in re.findall(r"(\w+): '(#[0-9a-f]{6})'", PAL_TS)}
INK = PALETTE['ink']
# Teal is reserved for actions in the UI, so world tiles never use it.
TILE_PALETTE = [v for k, v in PALETTE.items() if not k.startswith('teal')]
warnings.filterwarnings('ignore', category=DeprecationWarning)

# Shade families, darkest to lightest: shadow, rim, body, highlight.
FAMILIES = {
    'panel': ['sand', 'line', 'card', 'light'],
    'inset': ['line', 'card2', 'paper', 'card'],
    'secondary': ['sand', 'line', 'card2', 'card'],
    'primary': ['tealDark', 'teal', 'teal', 'tealLight'],
    'danger': ['redDark', 'red', 'red', 'redLight'],
    'attn': ['amberDark', 'amber', 'amber', 'amberLight'],
}

UI = {
    # name: (vendor file, family, top, right, bottom, left) — slice sizes of the compact crop before outlining
    'panel': ('kenney-pixel-ui/ancient-tan.png', 'panel', 3, 3, 4, 3),
    'inset': ('kenney-pixel-ui/ancient-tan_pressed.png', 'inset', 3, 3, 3, 3),
    'btn-secondary': ('kenney-pixel-ui/ancient-tan.png', 'secondary', 3, 3, 4, 3),
    'btn-secondary-pressed': ('kenney-pixel-ui/ancient-tan_pressed.png', 'secondary', 3, 3, 3, 3),
    'btn-primary': ('kenney-pixel-ui/colored-green.png', 'primary', 3, 3, 5, 3),
    'btn-primary-pressed': ('kenney-pixel-ui/colored-green_pressed.png', 'primary', 3, 3, 3, 3),
    'btn-danger': ('kenney-pixel-ui/colored-red.png', 'danger', 3, 3, 5, 3),
    'btn-danger-pressed': ('kenney-pixel-ui/colored-red_pressed.png', 'danger', 3, 3, 3, 3),
    'btn-attn': ('kenney-pixel-ui/colored-yellow.png', 'attn', 3, 3, 5, 3),
}
MID = 2  # stretchable middle, in art pixels


def lum(c):
    return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2]


def nearest(c):
    best, bd = None, 1e18
    for v in TILE_PALETTE:
        d = 2 * (c[0] - v[0]) ** 2 + 4 * (c[1] - v[1]) ** 2 + 3 * (c[2] - v[2]) ** 2
        if d < bd:
            best, bd = v, d
    return best


def outline(im):
    """Add a 1 px ink outline on transparent pixels that touch opaque ones (4-neighbour)."""
    w, h = im.size
    src = im.copy()
    big = Image.new('RGBA', (w + 2, h + 2), (0, 0, 0, 0))
    big.paste(src, (1, 1))
    px = big.load()
    sp = big.copy().load()
    for y in range(h + 2):
        for x in range(w + 2):
            if sp[x, y][3] > 0:
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < w + 2 and 0 <= ny < h + 2 and sp[nx, ny][3] > 0:
                    px[x, y] = (*INK, 255)
                    break
    return big


def compact(im, t, r, b, l):
    """Corners and edges of a nine-slice, with the middle shrunk to MID pixels."""
    w, h = im.size
    cw, ch = l + MID + r, t + MID + b
    out = Image.new('RGBA', (cw, ch), (0, 0, 0, 0))
    xs = list(range(l)) + [w // 2] * MID + list(range(w - r, w))
    ys = list(range(t)) + [h // 2] * MID + list(range(h - b, h))
    for oy, sy in enumerate(ys):
        for ox, sx in enumerate(xs):
            out.putpixel((ox, oy), im.getpixel((sx, sy)))
    return out


def family_map(im, family):
    cols = sorted({p[:3] for p in im.getdata() if p[3] > 0}, key=lum)
    shades = [PALETTE[n] for n in FAMILIES[family]]
    # Spread the source shades over the four target shades by rank.
    m = {}
    for i, c in enumerate(cols):
        k = 0 if len(cols) == 1 else round(i * (len(shades) - 1) / (len(cols) - 1))
        m[c] = shades[k]
    data = [(*m[p[:3]], 255) if p[3] > 0 else (0, 0, 0, 0) for p in im.getdata()]
    out = Image.new('RGBA', im.size)
    out.putdata(data)
    return out


def main():
    (OUT / 'ui').mkdir(parents=True, exist_ok=True)
    slices = []
    for name, (path, fam, t, r, b, l) in UI.items():
        im = Image.open(VENDOR / path).convert('RGBA')
        im = outline(family_map(compact(im, t, r, b, l), fam))
        im.save(OUT / 'ui' / f'{name}.png')
        slices.append(f"  '{name}': {{ top: {t + 1}, right: {r + 1}, bottom: {b + 1}, left: {l + 1} }},")
    (OUT / 'ui' / 'slices.ts').write_text(
        '/** Generated by scripts/unify-assets.py: nine-slice insets in art pixels (outline included). */\n'
        'export const SLICES = {\n' + '\n'.join(slices) + '\n} as const\n'
    )

    tiles_dir = VENDOR / 'kenney-tiny-town/tiles'
    cols, size = 12, 16
    sheet = Image.new('RGBA', (cols * size, 11 * size), (0, 0, 0, 0))
    for f in sorted(tiles_dir.glob('tile_*.png')):
        i = int(f.stem.split('_')[1])
        im = Image.open(f).convert('RGBA')
        data = [(*nearest(p[:3]), 255) if p[3] > 0 else (0, 0, 0, 0) for p in im.getdata()]
        im.putdata(data)
        sheet.paste(im, ((i % cols) * size, (i // cols) * size))
    sheet.save(OUT / 'tiles.png')
    print('wrote', len(UI), 'ui slices and tiles.png')


if __name__ == '__main__':
    main()
