/**
 * Generated by scripts/build-district.py. The south district (the gauntlet loop), painted in
 * src/assets/pixel/district.png. Edit the script, not this file.
 */
export const DISTRICT_TOP = 537
export const DISTRICT_COLS = 19
export const DISTRICT_ROWS = 36
export const TILE = 16
export const DISTRICT_BLOCKED: readonly string[] = [
  '...###.........#...',
  '#..####.....#.....#',
  '#..####.....#.....#',
  '...................',
  '....####...###.....',
  '....####...###.....',
  '#...####...###....#',
  '#.................#',
  '...................',
  '.....#......#......',
  '.....#...#..#......',
  '#...####...###....#',
  '#...####...###....#',
  '....####...###.....',
  '...................',
  '#.................#',
  '#.................#',
  '...................',
  '...................',
  '.#.#####...#####.#.',
  '.#...............#.',
  '.#######...#######.',
  '.#######...#######.',
  '.#######...#######.',
  '...................',
  '.......#...#.......',
  '.......#...#.......',
  '..#####.....####...',
  '..######...#####...',
  '..######...#####...',
  '...................',
  '..######...######..',
  '..#...#.....#...#..',
  '..#...#.....#...#..',
  '#...#...#.#...#...#',
  '#...#...#.#...#...#',
]
/** Where to stand to go in (the tile in front of each door). */
export const DISTRICT_DOORS = {
  tech: { x: 72, y: 593 },
  gov: { x: 104, y: 657 },
  rental: { x: 200, y: 657 },
  shop: { x: 104, y: 769 },
  cafe: { x: 200, y: 769 },
} as const
/** Buildings just for show on Main Street: the spot in front of each, where its name sign goes. */
export const DISTRICT_SIGNS = {
  bakery: { x: 40, y: 929 },
  clinic: { x: 104, y: 929 },
  library: { x: 216, y: 929 },
  hotel: { x: 264, y: 929 },
  school: { x: 72, y: 1025 },
  pharmacy: { x: 232, y: 1025 },
} as const
